spring.application.name: kafka-streams-xml-parsing

spring.cloud.stream.kafka.streams.binder.configuration.commit.interval.ms: 1000

spring.cloud.stream.kafka.streams.binder.configuration:
  default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
  default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde

spring.cloud.stream.bindings.process-in-0:
  destination: examResults
  
spring.cloud.stream.bindings.process-out-0:
  destination: studentInfo

spring.cloud.stream.bindings.process-out-1:
  destination: resultInfo